#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/3ca98880-2cb5-49c5-a5ca-44428e237b3d 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  int potValue;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#define potPin A1
#define ledPin 2

int ledPinValue = 0;
void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  pinMode(potPin,INPUT);
  pinMode(ledPin,OUTPUT);
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  int potReading = analogRead(potPin);
  potValue = map(potReading,0,1023,0,270);
  ledPinValue = potReading / 4;
  analogWrite(ledPin,ledPinValue)
  Serial.print("Pot value is");
  Serial.println(potValue);
  Serial.print("Led value is");
  Serial.println(ledPinValue);
  delay(10);
}


